Repository aspnet/AspNetCore.Docs.fr-fr, pull requests merged in 2018-03, with the labels that each got.

#49 French Improvment for aspnetcore/security/app-secrets.md
  aspnetcore/security/app-secrets.md
Labels: Accepted, Linguistic Suggestion

#37 French translation improvement aspnetcore/security/key-vault-configuration.md part 1/3
  aspnetcore/security/key-vault-configuration.md
Labels: Accepted, Linguistic Suggestion

#38 French translation improvement aspnetcore/security/key-vault-configuration.md part 2/3
  aspnetcore/security/key-vault-configuration.md
Labels: Accepted, Linguistic Suggestion

#39 French translation improvement aspnetcore/security/enforcing-ssl.md
  aspnetcore/security/enforcing-ssl.md
Labels: Accepted, Linguistic Suggestion

#28 Update view-compilation.md
  aspnetcore/mvc/views/view-compilation.md
Labels: Accepted, Linguistic Suggestion

#98 portable-object-localization.md
  aspnetcore/fundamentals/portable-object-localization.md
Labels: Accepted, Linguistic Suggestion

#85 Update aspnet/core/host-and-deploy/directory-structure.md
  aspnetcore/host-and-deploy/directory-structure.md
Labels: Accepted, Linguistic Suggestion

#61 French Improvment on aspnetcore/security/authorization/views.md
  aspnetcore/security/authorization/views.md
Labels: Accepted, Linguistic Suggestion

#59 French Improvment authentication/identity-primary-key-configuration.md
  aspnetcore/security/authentication/identity-primary-key-configuration.md
Labels: Accepted, Linguistic Suggestion

#74 Update overview.md
  aspnetcore/mvc/views/overview.md
Labels: Accepted, Linguistic Suggestion

#87 Update aspnetcore/data/ef-rp/read-related-data.md
  aspnetcore/data/ef-rp/read-related-data.md
Labels: Accepted, Linguistic Suggestion

#89 Update distributed.md
  aspnetcore/performance/caching/distributed.md
Labels: Accepted, Linguistic Suggestion

#81 Update overview.md
  aspnetcore/mvc/views/overview.md
Labels: Accepted, Linguistic Suggestion

#71 Update aspnetcore/host-and-deploy/ihostingstartup.md
  aspnetcore/host-and-deploy/ihostingstartup.md
Labels: Accepted, Linguistic Suggestion

#70 Update overview.md
  aspnetcore/mvc/overview.md
Labels: Accepted, Linguistic Suggestion

#22 Update aspnetcore/index.md
  aspnetcore/index.md
Labels: Accepted, Linguistic Suggestion

#40 Update aspnetcore/mvc/overview.md
  aspnetcore/mvc/overview.md
Labels: Accepted, Linguistic Suggestion

#55 French update aspnetcore/security/authorization/introduction.md + Add link to doc
  aspnetcore/security/authorization/introduction.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#63 French Improvment for aspnetcore/migration/configuration.md
  aspnetcore/migration/configuration.md
Labels: Accepted, Linguistic Suggestion

#65 Update aspnetcore/fundamentals/servers/aspnet-core-module.md
  aspnetcore/fundamentals/servers/aspnet-core-module.md
Labels: Accepted, Linguistic Suggestion

#52 French Improvment for aspnetcore/security/authentication/community.md
  aspnetcore/security/authentication/community.md
Labels: Accepted, Linguistic Suggestion

#48 French Improvment for aspnetcore/security/authorization/simple.md
  aspnetcore/security/authorization/simple.md
Labels: Accepted, Linguistic Suggestion

#35 Update aspnetcore/security/authentication/community.md
  aspnetcore/security/authentication/community.md
Labels: In Progress, Linguistic Suggestion

#43 Client-side development: translate the index page in french
  aspnetcore/client-side/index.md
Labels: Accepted, Linguistic Suggestion

#90 Update native-mobile-backend.md
  aspnetcore/mobile/native-mobile-backend.md
Labels: Accepted, Linguistic Suggestion

#80 Update aspnetcore/migration/mvc.md
  aspnetcore/migration/mvc.md
Labels: Accepted, Linguistic Suggestion

#26 Update aspnetcore/performance/caching/memory.md
  aspnetcore/performance/caching/memory.md
Labels: In Progress, Linguistic Suggestion

#93 Somes traductions corrections
  aspnetcore/security/authorization/roles.md
Labels: Accepted, Linguistic Suggestion

#79 Update aspnetcore/data/ef-rp/migrations.md
  aspnetcore/data/ef-rp/migrations.md
Labels: Accepted, Linguistic Suggestion

#76 Update aspnetcore/performance/response-compression.md
  aspnetcore/performance/response-compression.md
Labels: Accepted, Linguistic Suggestion

#75 Update aspnetcore/data/ef-rp/crud.md
  aspnetcore/data/ef-rp/crud.md
Labels: Accepted, Linguistic Suggestion

#60 Update aspnetcore/mvc/models/model-binding.md
  aspnetcore/mvc/models/model-binding.md
Labels: Accepted, Linguistic Suggestion

#32 Update aspnetcore/mobile/native-mobile-backend.md
  aspnetcore/mobile/native-mobile-backend.md
Labels: Accepted, Linguistic Suggestion

#33 Update aspnetcore/fundamentals/environments.md
  aspnetcore/fundamentals/environments.md
Labels: Accepted, Linguistic Suggestion

#36 Update aspnetcore/performance/caching/response.md
  aspnetcore/performance/caching/response.md
Labels: In Progress, Linguistic Suggestion

#44 Update dependency-injection.md
  aspnetcore/fundamentals/dependency-injection.md
Labels: Accepted, Linguistic Suggestion

#21 Update using-gulp.md
  aspnetcore/client-side/using-gulp.md
Labels: Accepted, Linguistic Suggestion

#31 Update aspnetcore/mvc/views/tag-helpers/intro.md
  aspnetcore/mvc/views/tag-helpers/intro.md
Labels: Accepted, Linguistic Suggestion

#77 Update aspnetcore/data/ef-mvc/sort-filter-page.md
  aspnetcore/data/ef-mvc/sort-filter-page.md
Labels: Accepted, Linguistic Suggestion
